Protocol: http
Host: 127.0.0.1
Port: 9090
MaxMemory: 5000
MaxCPU: 50
Bootstrap: true
NodeId: 1
RaftAddress: 127.0.0.1:7070
RaftTransportMaxPool: 100
RaftTransportTimeout: 1
RaftApplyTimeout: 2
RaftSnapshotInterval: 1
RaftSnapshotThreshold: 1
PeerConnectRetryMax: 2
PeerConnectRetryDelay: 1
PeerAuthRequestTimeoutMs: 2
JobExecutionTimeout: 30
JobExecutionRetryDelay: 1
JobExecutionRetryMax: 10
JobInvocationDebounceDelay: 100
IncomingRequestMaxWorkers: 1
IncomingRequestMaxQueue: 1
JobQueueDebounceDelay: 1
ExecutionLogFetchFanIn: 2
ExecutionLogFetchInterval: 2
Replicas:
  - Address: http://127.0.0.1:9090
    RaftAddress: 127.0.0.1:7070
    NodeId: 1