version: 2.1
jobs:

  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Run Database
          command: |
            docker run --name postgres -e POSTGRES_USER=core -e POSTGRES_PASSWORD=localdev -e POSTGRES_DB=scheduler0_test -p 5432:5432 -d postgres
      - run:
          name: Run Test
          command: |
            docker-compose -f ./docker/docker-compose.ci.yml up -d server
workflows:
  build:
    jobs:
      - build
