version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: go get -t -v ./...

      - run:
          name: Run tests
          command: |
            go install github.com/mattn/goveralls@latest
            go test -v -cover -coverprofile=./coverage.out ./...
      - run:
          name: Upload coverage to Coveralls
          command: goveralls -coverprofile=./coverage.out -service=circle-ci -repotoken $COVERALLS_TOKEN -coverprofile=./coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN