version: 2.1
jobs:

  build:
    machine:
        image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Run Database
          command: |
            docker run --name postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d postgres
      - run:
          name: Run Test
          command: |
            docker-compose -f ./docker/docker-compose.ci.yml up -d server
workflows:
    build:
      jobs:
        - build
