version: 2.1
jobs:

  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Create DB Image
          command: |
            docker build -t scheduler0:postgres ./docker/postgres
      - run:
          name: Run Database
          command: |
            docker run -d -p 5432:5432 scheduler0:postgres
      - run:
          name: Run Test
          command: |
            docker-compose -f ./docker/docker-compose.ci.yml up -d server
workflows:
  build:
    jobs:
      - build
