version: '3.4'

services:

  server:
    build:
      context: ..
      dockerfile: ./docker/server/Dockerfile
      args:
        PORT: 4321
        POSTGRES_ADDRESS: postgres:5432
        POSTGRES_DATABASE: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        BASIC_AUTH_USER: admin
        BASIC_AUTH_PASS: admin
      network: host
    ports:
      - "4321:4321"
    depends_on:
      - postgres
    environment:
      POSTGRES_ADDRESS: postgres:5432
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      BASIC_AUTH_USER: admin
      BASIC_AUTH_PASS: admin
      PORT: 4321
    networks:
      - default

  client:
    build:
      context: ..
      dockerfile: ./docker/client/Dockerfile.dev
      args:
        NODE_ENV: development
        PORT: 4327
        API_ENDPOINT: http://server:4321
        BASIC_AUTH_USER: admin
        BASIC_AUTH_PASS: admin
    ports:
      - "4327:4327"
      - "9229:9229"
    depends_on:
      - server
    networks:
      - default
    volumes:
      - ./client:/usr/src/client
    environment:
      NODE_ENV: development
      PORT: 4327
      API_ENDPOINT: http://server:4321
      BASIC_AUTH_USER: admin
      BASIC_AUTH_PASS: admin

  postgres:
    image: postgres:13-alpine
    networks:
      - default
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
