version: '3.4'

services:

  server:
    build:
      context: ../
      dockerfile: ./docker/server/Dockerfile.server-test
      network: host
      args:
        PORT: 4321
        POSTGRES_ADDRESS: localhost:5432
        POSTGRES_DATABASE: scheduler0_test
        POSTGRES_USER: core
        POSTGRES_PASSWORD: localdev
    ports:
      - "4321:4321"
    volumes:
      - ./server:/usr/src/server
    environment:
      POSTGRES_ADDRESS: localhost:5432
      POSTGRES_DATABASE: scheduler0_test
      POSTGRES_USER: core
      POSTGRES_PASSWORD: localdev
    networks:
      - default
