version: '3.4'

services:

  server:
    build:
      context: ../server
      dockerfile: docker/Dockerfile.server-test
      network: host
      args:
        PORT: 4321
        POSTGRES_ADDRESS: localhost:5432
        POSTGRES_DATABASE: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
      - "4321:4321"
    volumes:
      - ./server:/usr/src/server
    environment:
      POSTGRES_ADDRESS: localhost:5432
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - default
